vocab = [
    "Ä, ab + abl (also used as prefix with verbs)#from, by (as prefix = away)#p#a:ab#from:by#21",
    "absum, abesse#be out, be absent, be away#v#absum:abesse#be out:be absent:be away#6",
    "ac, atque (indecl.)#and#x#ac:atque:et:-que:que#and#28",
    "accidÅ, accidere, accidÄ«#happen#v#accido:accidere#happen#25",
    "accipiÅ, accipere, accÄ“pÄ«, acceptus#accept, take in, receive#v#accipio:accipere#accept:take in:receive#10",
    "ad + acc (also used as prefix with verbs)#to, towards, at#p#ad#to:towards:at#3",
    "adeÅ (indecl.)#so much, so greatly#d#adeo#so much:so greatly#27",
    "adiuvÅ, adiuvÄre, adiÅ«vÄ«, adiÅ«tus#help#v#adiuvo:adiuvare#help#21",
    "adsum, adesse#be here, be present#v#adsum:adesse#be here:be present#5",
    "adveniÅ, advenÄ«re, advÄ“nÄ«#arrive#v#advenio:advenire#arrive#13",
    "agÅ, agere, Ä“gÄ«, Äctus#do, act, drive#v#ago:agere#do:act:drive#4",
    "aliquis, aliquid#someone, something#r#aliquis:aliquid#someone:something#14",
    "alius, alia, aliud#other, another, else#ar#alius#other:another:else#15",
    "alter, altera, alterum#the other, another, the second of two#ar#alter#the other:another:the second of two:other:second of two#13",
    "altus, alta, altum#high, deep#a#altus#high:deep#31",
    "ambulÅ, ambulÄre, ambulÄvÄ«#walk#v#ambulo:ambulare#walk#5",
    "amÄ«cus, amÄ«cÄ«, m.#friend#n#amicus#friend#2",
    "amÅ, amÄre, amÄvÄ«, amÄtus#love, like#v#amo:amare:amor#love:like#19",
    "amor, amÅris, m.#love#n#amo:amor#love#22",
    "ancilla, ancillae, f.#slave-girl, maid#n#ancilla#slave-girl:slave girl:slavegirl:maid#2",
    "animus, animÄ«, m.#spirit, soul, mind#n#animus#spirit:soul:mind#17",
    "annus, annÄ«, m.#year#n#annus#year#21",
    "ante + acc#before, in front of#p#ante#before:in front of#31",
    "anteÄ (indecl.)#before#d#antea#before#27",
    "aperiÅ, aperÄ«re, aperuÄ«, apertus#open#v#aperio:aperire#open#25",
    "appÄreÅ, appÄrÄ“re, appÄruÄ«#appear#v#appareo:apparere#appear#27",
    "appropinquÅ, appropinquÄre, appropinquÄvÄ« + dat#approach, come near to#v#appropinquo:appropinquare#approach:come near to#17",
    "apud + acc#among, with, at the house of#p#apud#among:with:at the house of#14",
    "aqua, aquae, f.#water#n#aqua#water#15",
    "audÄx, audÄcis#bold, daring#a#audax#bold:daring#24",
    "audiÅ, audÄ«re, audÄ«vÄ«, audÄ«tus#hear, listen to#v#audio:audire#hear:listen to#5",
    "auferÅ, auferre, abstulÄ«, ablÄtus#take away, carry off, steal#v#aufero:auferre#take away:carry off:steal#26",
    "aut ... aut (indecl.)#either ... or ...#x#aut aut#either or#39",
    "bellum, bellÄ«, n.#war#n#bellum#war#26",
    "bene (indecl.)#well#d#bene#well#17",
    "benignus, benigna, benignum#kind, generous#a#benignus#kind:generous#17",
    "bibÅ, bibere, bibÄ«#drink#v#bibo:bibere#drink#3",
    "bonus, bona, bonum#good#a#bonus#good#16",
    "brevis, breve#short, brief#a#brevis#short:brief#0",
    "cadÅ, cadere, cecidÄ«, cÄsus#fall#v#cado:cadere#fall#39",
    "caelum, caelÄ«, n.#sky, heaven#n#caelum#sky:heaven#22",
    "canis, canis, m.#dog#n#canis#dog#1",
    "capiÅ, capere, cÄ“pÄ«, captus#take, catch, capture, adopt (a plan)#v#capio:capere#take:catch:capture:adopt#11",
    "caput, capitis, n.#head#n#caput#head#18",
    "cÄrus, cÄra, cÄrum#dear#a#carus#dear#19",
    "celer, celere#quick, fast#a#celer#quick:fast#9",
    "cÄ“lÅ, cÄ“lÄre, cÄ“lÄvÄ«, cÄ“lÄtus#hide#v#celo:celare#hide#21",
    "cÄ“na, cÄ“nae, f.#dinner, meal#n#cena#dinner:meal#2",
    "centum (indecl.)#a hundred#a#centum#a hundred#28",
    "cÄ“terÄ«, cÄ“terae, cÄ“tera#the rest, the others#a#ceteri#the rest:the others#13",
    "cibus, cibÄ«, m.#food#n#cibus#food#2",
    "circum + acc#around#p#circum#around#21",
    "cÄ«vis, cÄ«vis, m.f.#citizen#n#civis#citizen#11",
    "clÄmÅ, clÄmÄre, clÄmÄvÄ«, clÄmÄtus#shout#v#clamo:clamare:clamor:vox#shout#3",
    "clÄmor, clÄmÅris, m.#shout, shouting, noise#n#clamo:clamor:vox#shout:shouting:noise#5",
    "coepÄ«, coepisse, coeptus#began (past tenses only)#v#coepi:coepisse#began#18",
    "cÅgitÅ, cÅgitÄre, cÅgitÄvÄ«, cÅgitÄtus#think, consider#v#cogito:cogitare:puto:putare#think:consider#19",
    "cognÅscÅ, cognÅscere, cognÅvÄ«, cognitus#get to know, find out, learn#v#cognosco:cognoscere#get to know:find out:learn#18",
    "cÅgÅ, cÅgere, coÄ“gÄ«, coÄctus#force, compel#v#cogo:cogere#force:compel#25",
    "comes, comitis, m.f.#comrade, companion#n#comes#comrade:companion#27",
    "cÅnficiÅ, cÅnficere, cÅnfÄ“cÄ«, cÅnfectus#finish; wear out, exhaust#v#conficio:conficere#finish:wear out:exhaust#19",
    "cÅnor, cÅnÄrÄ«, cÅnÄtus sum#try#v#conor:conari#try#34",
    "cÅnsilium, cÅnsiliÄ«, n.#plan, idea, advice#n#consilium#plan:idea:advice#16",
    "cÅnspiciÅ, cÅnspicere, cÅnspexÄ«, cÅnspectus#catch sight of, notice#v#conspicio:conspicere#catch sight of:notice#7",
    "cÅnstituÅ, cÅnstituere, cÅnstituÄ«, cÅnstitÅ«tus#decide#v#constituo:constituere#decide#28",
    "cÅnsÅ«mÅ, cÅnsÅ«mere, cÅnsÅ«mpsÄ«, cÅnsÅ«mptus#eat#v#consumo:consumere#eat#8",
    "contrÄ + acc#against#p#contra#against#33",
    "corpus, corporis, n.#body#n#corpus#body#28",
    "crÄ“dÅ, crÄ“dere, crÄ“didÄ«, crÄ“ditus + dat#believe, trust, have faith in#v#credo:credere#believe:trust:have faith in#11",
    "crÅ«dÄ“lis, crÅ«dÄ“le#cruel#a#crudelis:saevus#cruel#20",
    "cum + abl (as prefix col- / com- / con- / cor-)#with (as prefix = together)#p#cum#with#7",
    "cum (indecl.)#when, since#x#cum#when:since#24",
    "cupiÅ, cupere, cupÄ«vÄ«#want, desire#v#cupio:cupere:volo:velle#want:desire#9",
    "cÅ«r? (indecl.)#why?#d#cur#why#4",
    "cÅ«ra, cÅ«rae, f.#care, worry#n#cura#care:worry#23",
    "cÅ«rÅ, cÅ«rÄre, cÅ«rÄvÄ«, cÅ«rÄtus#look after, care for, supervise#v#curo:curare#look after:care for:supervise#19",
    "currÅ, currere, cucurrÄ«, cursus#run#v#curro:currere#run#5",
    "custÅs, custÅdis, m.f.#guard#n#custos#guard#13",
    "dÄ“ + abl (also used as prefix with verbs)#from, down from; about (as prefix = down)#p#de#from:down from:about#11",
    "dea, deae, f.#goddess#n#dea#goddess#18",
    "dÄ“beÅ, dÄ“bÄ“re, dÄ“buÄ«, dÄ“bitus#owe, ought, should, must#v#debeo:debere#owe:ought:should:must#15",
    "decem (indecl.)#ten#a#decem#ten#20",
    "deinde (indecl.)#then#d#deinde:tum#then#16",
    "dÄ“leÅ, dÄ“lÄ“re, dÄ“lÄ“vÄ«, dÄ“lÄ“tus#destroy#v#deleo:delere#destroy#14",
    "dÄ“spÄ“rÅ, dÄ“spÄ“rÄre, dÄ“spÄ“rÄvÄ«, dÄ“spÄ“rÄtus#despair#v#despero:desperare#despair#20",
    "deus, deÄ«, m.#god#n#deus#god#14",
    "dÄ«cÅ, dÄ«cere, dÄ«xÄ«, dictus#say#v#dico:dicere:inquit#say#13",
    "diÄ“s, diÄ“Ä«, m.#day#n#dies#day#9",
    "difficilis, difficile#difficult#a#difficilis#difficult#14",
    "dÄ«rus, dÄ«ra, dÄ«rum#dreadful#a#dirus#dreadful#0",
    "discÄ“dÅ, discÄ“dere, discessÄ«#depart, leave#v#discedo:discedere:relinquo:relinquere#depart:leave#18",
    "diÅ« (indecl.)#for a long time#d#diu#for a long time#17",
    "dÄ«ves, dÄ«vitis#rich#a#dives#rich#30",
    "dÅ, dare, dedÄ«, datus#give#v#do:dare#give#9",
    "domÄ«#at home#d#domi#at home#0",
    "domina, dominae, f.#mistress#n#domina#mistress#14",
    "dominus, dominÄ«, m.#master#n#dominus#master#2",
    "domus, domÅ«s, f.#home, house#n#domus#home:house#20",
    "dÅnum, dÅnÄ«, n.#gift, present#n#donum#gift:present#14",
    "dormiÅ, dormÄ«re, dormÄ«vÄ«#sleep#v#dormio:dormire#sleep#2",
    "dÅ«cÅ, dÅ«cere, dÅ«xÄ«, ductus#lead, take#v#duco:ducere#lead:take#8",
    "dum#while#x#dum#while#34",
    "duo, duae, duo#two#a#duo#two#12",
    "dÅ«rus, dÅ«ra, dÅ«rum#hard, harsh#a#durus#hard:harsh#21",
    "dux, ducis, m.#leader#n#dux#leader#0",
    "Ä“, ex + abl (also used as prefix with verbs)#from, out of (as prefix = out, away)#p#e:ex#from:out of#4",
    "effugiÅ, effugere, effÅ«gÄ«#escape#v#effugio:effugere#escape#16",
    "ego, meÄ«#I, me#r#ego:mei#I:me#4",
    "Ä“gredior, Ä“gredÄ«, Ä“gressus sum#go out#v#egredior:egredi#go out#34",
    "emÅ, emere, Ä“mÄ«, Ä“mptus#buy#v#emo:emere#buy#6",
    "enim (indecl.)#for#x#enim:nam#for#23",
    "eÅ, Ä«re, iÄ«#go#v#eo:ire#go#11",
    "epistula, epistulae, f.#letter#n#epistula#letter#12",
    "equus, equÄ«, m.#horse#n#equus#horse#15",
    "et (indecl.)#and#x#ac:atque:et:-que:que#and#3",
    "etiam (indecl.)#also, even#d#etiam:quoque#also:even#15",
    "exspectÅ, exspectÄre, exspectÄvÄ«, exspectÄtus#wait for#v#exspecto:exspectare#wait for#3",
    "facilis, facile#easy#a#facilis#easy#17",
    "faciÅ, facere, fÄ“cÄ«, factus#make, do#v#facio:facere#make:do#7",
    "fÄ“mina, fÄ“minae, f.#woman#n#femina#woman#5",
    "ferÅ, ferre, tulÄ«, lÄtus#bring, carry, bear#v#fero:ferre:porto:portare#bring:carry:bear#9",
    "ferÅx, ferÅcis#fierce, ferocious#a#ferox#fierce:ferocious#8",
    "festÄ«nÅ, festÄ«nÄre, festÄ«nÄvÄ«#hurry#v#festino:festinare#hurry#6",
    "fidÄ“lis, fidÄ“le#faithful, loyal#a#fidelis#faithful:loyal#14",
    "fÄ«lia, fÄ«liae, f.#daughter#n#filia#daughter#19",
    "fÄ«lius, fÄ«liÄ«, m.#son#n#filius#son#1",
    "flÅ«men, flÅ«minis, n.#river#n#flumen#river#24",
    "forte (indecl.)#by chance#d#forte#by chance#19",
    "fortis, forte#brave#a#fortis#brave#6",
    "forum, forÄ«, n.#forum, market place#n#forum#forum:market place#0",
    "frangÅ, frangere, frÄ“gÄ«, frÄctus#break#v#frango:frangere#break#34",
    "frÄter, frÄtris, m.#brother#n#frater#brother#10",
    "frÅ«strÄ (indecl.)#in vain#d#frustra#in vain#12",
    "fugiÅ, fugere, fÅ«gÄ«#run away, flee#v#fugio:fugere#run away:flee#12",
    "gerÅ, gerere, gessÄ«, gestus#wear (clothes), wage (war)#v#gero:gerere#wear:wage#23",
    "gladius, gladiÄ«, m.#sword#n#ferrum:gladius#sword#8",
    "gravis, grave#heavy, serious#a#gravis#heavy:serious#21",
    "habeÅ, habÄ“re, habuÄ«, habitus#have#v#habeo:habere#have#4",
    "habitÅ, habitÄre, habitÄvÄ«, habitÄtus#live#v#habito:habitare:vivo:vivere#live#10",
    "heri (indecl.)#yesterday#d#heri#yesterday#7",
    "hÄ«c (indecl.)#here#d#hic#here#33",
    "hic, haec, hoc#this#r#hic#this#8",
    "hodiÄ“ (indecl.)#today#d#hodie#today#5",
    "homÅ, hominis, m.#man, human being, person#n#homo#man:human being:person#9",
    "hÅra, hÅrae, f.#hour#n#hora#hour#21",
    "hortus, hortÄ«, m.#garden#n#hortus#garden#1",
    "hostis, hostis, m.#enemy#n#hostis#enemy#22",
    "iaceÅ, iacÄ“re, iacuÄ«#lie (positional)#v#iaceo:iacere#lie#12",
    "iaciÅ, iacere, iÄ“cÄ«, iactus#throw#v#iacio:iacere#throw#23",
    "iam (indecl.)#now, already#d#iam#now:already#12",
    "iÄnua, iÄnuae, f.#door#n#ianua#door#3",
    "ibi (indecl.)#there#d#ibi#there#18",
    "igitur (indecl.)#therefore, and so#d#igitur:itaque#therefore:and so#12",
    "ignis, ignis, m.#fire#n#ignis#fire#36",
    "ille, illa, illud#that, he, she, it#r#ille#that:he:she:it#9",
    "imperÄtor, imperÄtÅris, m.#emperor, commander, general#n#imperator#emperor:commander:general#16",
    "imperium, imperiÄ«, n.#empire, power, command#n#imperium#empire:power:command#10",
    "imperÅ, imperÄre, imperÄvÄ«, imperÄtus + dat#order, command#v#impero:imperare:iubeo:iubere#order:command#27",
    "in + acc (also used as prefix with verbs)#into, onto#p#in#into:onto#1",
    "in + abl (also used as prefix with verbs)#in, on#p#in#in:on#1",
    "incendÅ, incendere, incendÄ«, incÄ“nsus#burn, set on fire#v#iincendo#burn:set on fire#27",
    "Ä«nfÄ“lÄ«x, Ä«nfÄ“lÄ«cis#unlucky, unhappy#a#infelix#unlucky:unhappy#21",
    "ingÄ“ns, ingentis#huge#a#ingens#huge#7",
    "ingredior, ingredÄ«, ingressus sum#enter#v#ingredior:ingredi#enter#34",
    "inquit#say, said#v#dico:dicere:inquit#say:said#4",
    "Ä«nsula, Ä«nsulae, f.#island, block of flats#n#insula#island:block of flats#17",
    "intellegÅ, intellegere, intellÄ“xÄ«, intellÄ“ctus#understand, realise#v#intellego:intellegere#understand:realise#7",
    "inter + acc#among, between#p#inter#among:between#16",
    "interea (indecl.)#meanwhile#d#interea#meanwhile#24",
    "intrÅ, intrÄre, intrÄvÄ«, intrÄtus#enter#v#intro:intrare#enter#2",
    "inveniÅ, invenÄ«re, invÄ“nÄ«, inventus#find#v#invenio:invenire#find#10",
    "Ä«ra, Ä«rae, f.#anger#n#ira#anger#28",
    "Ä«rÄtus, Ä«rÄta, Ä«rÄtum#angry#a#iratus#angry#3",
    "is, ea, id#this, that, he, she, it, them#r#is#this:that:he:she:it:them#8",
    "ita (indecl.)#in this way, so#d#ita:sic#in this way:so#16",
    "ita vÄ“rÅ (indecl.)#yes#d#ita vero#yes#13",
    "itaque (indecl.)#and so, therefore#d#igitur:itaque#and so:therefore#17",
    "iter, itineris, n.#journey, route, way#n#iter#journey:route:way#19",
    "iterum (indecl.)#again#d#iterum#again#9",
    "iubeÅ, iubÄ“re, iussÄ«, iussus#order#v#impero:imperare:iubeo:iubere#order#21",
    "iuvenis, iuvenis (m.)#young; young man#an#iuvenis#young:young man#5",
    "labor, labÅris, m.#work#n#labor:laboro#work#0",
    "labÅrÅ, labÅrÄre, labÅrÄvÄ«#work#v#labor:laboro:laborare#work#1",
    "lacrimÅ, lacrimÄre, lacrimÄvÄ«#weep, cry#v#lacrimo:lacrimare#weep:cry#7",
    "laetus, laeta, laetum#happy#a#laetus#happy#2",
    "lÄtus, lÄta, lÄtum#wide#a#latus#wide#0",
    "laudÅ, laudÄre, laudÄvÄ«, laudÄtus#praise#v#laudo:laudare#praise#2",
    "lÄ“gÄtus, lÄ“gÄtÄ«, m.#commander#n#imperator:legatus#commander#26",
    "legiÅ, legiÅnis, f.#legion#n#legio#legion#26",
    "legÅ, legere, lÄ“gÄ«, lÄ“ctus#read, choose#v#lego:legere#read:choose#11",
    "lentÄ“ (indecl.)#slowly#d#lente#slowly#15",
    "libenter (indecl.)#willingly, gladly#d#libenter#willingly:gladly#18",
    "lÄ«berÄ«, lÄ«berÅrum, m.pl.#children#n#liberi#children#29",
    "lÄ«berÅ, lÄ«berÄre, lÄ«berÄvÄ«, lÄ«berÄtus#free, set free#v#libero:liberare#free:set free#20",
    "lÄ«bertus, lÄ«bertÄ«, m.#freedman, ex-slave#n#libertus#freedman:ex-slave:ex slave#6",
    "locus, locÄ«, m.#place#n#locus:pono#place#19",
    "longus, longa, longum#long#a#longus#long#0",
    "loquor, loquÄ«, locÅ«tus sum#speak#v#loquor:loqui#speak#34",
    "lÅ«x, lÅ«cis, f.#light, daylight#n#lux#light:daylight#0",
    "magnopere (indecl.)#greatly, very much#d#magnopere:valde#greatly:very much#30",
    "magnus, magna, magnum#big, large, great#a#magnus#big:large:great#3",
    "maior, maius (irregular comparative)#bigger, larger, greater#a#maior#bigger:larger:greater#0",
    "malus, mala, malum#evil, bad#a#malus#evil:bad#28",
    "maneÅ, manÄ“re, mÄnsÄ«#remain, stay#v#maneo:manere#remain:stay#9",
    "manus, manÅ«s, f.#hand, group of people#n#manus#hand:group of people#18",
    "mare, maris, n.#sea#n#mare#sea#15",
    "marÄ«tus, marÄ«tÄ«, m.#husband#n#maritus#husband#14",
    "mÄter, mÄtris, f.#mother#n#mater#mother#1",
    "maximus, maxima, maximum#the biggest, the greatest, very big, very great#a#maximus#the biggest:the greatest:biggest:greatest:very big:very great#17",
    "medius, media, medium#middle, middle of#a#medius#middle:middle of#9",
    "melior, melius (irregular comparative)#better#a#melior#better#16",
    "meus, mea, meum#my#a#meus#my#5",
    "mÄ«les, mÄ«litis, m.#soldier#n#miles#soldier#18",
    "mÄ«lle, pl. mÄ«lia#thousand#n#mille#thousand#28",
    "minimÄ“ (indecl.)#very little, least, no#d#minime#very little:least:no#11",
    "minimus, minima, minimum#very little, very small#a#minimus#very little:very small#22",
    "minor, minus (irregular comparative)#smaller, less#a#minor#smaller:less#0",
    "miser, misera, miserum#miserable, wretched, sad#a#miser:tristis#miserable:wretched:sad#15",
    "mittÅ, mittere, mÄ«sÄ«, missus#send#v#mitto:mittere#send#12",
    "modus, modÄ«, m.#manner, way, kind#n#modus#manner:way:kind#23",
    "mÅns, montis, m.#mountain#n#mons#mountain#12",
    "morior, morÄ«, mortuus sum#die#v#morior:mori#die#34",
    "mors, mortis, f.#death#n#mors#death#20",
    "mox (indecl.)#soon#d#mox#soon#9",
    "multÅ, multum (indecl.)#much#d#multo:multum:multus#much#0",
    "multus, multa, multum#much, many#a#multus#much:many#5",
    "mÅ«rus, mÅ«rÄ«, m.#wall#n#murus#wall#11",
    "nam (indecl.)#for#x#enim:nam#for#18",
    "nÄrrÅ, nÄrrÄre, nÄrrÄvÄ«, nÄrrÄtus#tell, relate#v#narro:narrare:refero:referre#tell:relate#7",
    "nauta, nautae, m.#sailor#n#nauta#sailor#15",
    "nÄvigÅ, nÄvigÄre, nÄvigÄvÄ«#sail#v#navigo:navigare#sail#16",
    "nÄvis, nÄvis, f.#ship#n#navis#ship#3",
    "nÄ“ (indecl.)#that ... not, so that ... not#x#ne#that not:so that not#31",
    "-ne (indecl.)#introduces question#x#-ne:ne#introduces question#0",
    "nec ... nec, neque ... neque (indecl.)#neither ... nor ...#x#nec nec:neque neque#neither nor#0",
    "necesse (indecl.)#necessary#n#necesse#necessary#14",
    "necÅ, necÄre, necÄvÄ«, necÄtus#kill#v#interficio:interficere:neco:necare:occido:occidere#kill#7",
    "nÄ“mÅ, nÄ“minis#no one, nobody#n#nemo#no one:nobody#18",
    "nescio, nescÄ«re, nescÄ«vÄ«#not know#v#nescio:nescire#not know#25",
    "nihil (indecl.)#nothing#n#nihil#nothing#7",
    "nÅlÅ, nÅlle, nÅluÄ«#not want#v#nolo:nolle#not want#13",
    "nÅmen, nÅminis, n.#name#n#nomen#name#25",
    "nÅn (indecl.)#not#d#non#not#3",
    "nÅnne? (indecl.)#surely?#d#nonne#surely#16",
    "nÅs, nostrum#we, us#r#nos#we:us#10",
    "noster, nostra, nostrum#our#r#noster#our#11",
    "novem (indecl.)#nine#a#novem#nine#20",
    "novus, nova, novum#new#a#novus#new#13",
    "nox, noctis, f.#night#n#nox#night#22",
    "nÅ«llus, nÅ«lla, nÅ«llum#not any, no#a#nullus#not any:no#13",
    "num (indecl.)#whether#x#num#whether#26",
    "num ... ? (indecl.)#surely not?#x#num#surely not#14",
    "numquam (indecl.)#never#d#numquam#never#17",
    "nunc (indecl.)#now#d#iam:nunc#now#11",
    "nÅ«ntiÅ, nÅ«ntiÄre, nÅ«ntiÄvÄ«, nÅ«ntiÄtus#announce, report#v#nuntio:nuntiare#announce:report#10",
    "nÅ«ntius, nÅ«ntiÄ«, m.#messenger, message, news#n#nuntius#messenger:message:news#8",
    "occÄ«dÅ, occÄ«dere, occÄ«dÄ«, occÄ«sus#kill#v#interficio:interficere:neco:necare:occido:occidere#kill#28",
    "octÅ (indecl.)#eight#a#octo#eight#20",
    "offerÅ, offerre, obtulÄ«, oblÄtus#offer#v#offero:offerre#offer#9",
    "Ålim (indecl.)#once, some time ago#d#olim#once:some time ago#6",
    "omnis, omne#all, every#a#omnis#all:every#7",
    "oppugnÅ, oppugnÄre, oppugnÄvÄ«, oppugnÄtus#attack#v#oppugno:oppugnare:peto:petere#attack#24",
    "optimus, optima, optimum#the best, very good, excellent#a#optimus#the best:best:very good:excellent#5",
    "ÅrÅ, ÅrÄre, ÅrÄvÄ«, ÅrÄtus#beg, beg for#v#oro:orare#beg:beg for#0",
    "ostendÅ, ostendere, ostendÄ«, ostentus#show#v#ostendo:ostendere#show#9",
    "paene (indecl.)#almost, nearly#d#paene#almost:nearly#12",
    "pÄreÅ, pÄrÄ“re, pÄruÄ« + dat#obey#v#pareo:parere#obey#23",
    "parÅ, parÄre, parÄvÄ«, parÄtus#prepare#v#paro:parare#prepare#7",
    "pars, partis, f.#part#n#pars#part#18",
    "parvus, parva, parvum#small#a#parvus#small#6",
    "pater, patris, m.#father#n#pater#father#1",
    "paucÄ«, paucae, pauca#few, a few#a#pauci#few:a few#17",
    "pÄx, pÄcis, f.#peace#n#pax#peace#10",
    "pecÅ«nia, pecÅ«niae, f.#money#n#pecunia#money#4",
    "peior, peius (irregular comparative)#worse#a#peior#worse#0",
    "per + acc (also used as prefix with verbs)#through, along#p#per#through:along#6",
    "pereÅ, perÄ«re, periÄ«#die, perish#v#pereo:perire#die:perish#16",
    "perÄ«culum, perÄ«culÄ«, n.#danger#n#periculum#danger#19",
    "persuÄdeÅ, persuÄdÄ“re, persuÄsÄ« + dat#persuade#v#persuadeo:persuadere#persuade#20",
    "perterritus, perterrita, perterritum#terrified#a#perterritus#terrified#4",
    "pÄ“s, pedis, m.#foot, paw#n#pes#foot:paw#8",
    "pessimus, pessima, pessimum#the worst, very bad#a#pessimus#the worst:worst:very bad#20",
    "petÅ, petere, petÄ«vÄ«, petÄ«tus#make for, attack, seek, beg, ask for#v#peto:petere#make for:attack:seek:beg:ask for#5",
    "placeÅ, placÄ“re, placuÄ« + dat#please#v#placeo:placere#please#11",
    "plÄ“nus, plÄ“na, plÄ“num#full#a#plenus#full#21",
    "plus, pluris (irregular comparative)#more#a#plus#more#21",
    "poena, poenae, f.#punishment#n#poena#punishment#25",
    "poenÄs dÅ, dare, dedÄ«, datus#pay the penalty, be punished#v#poenas do:poenas dare#pay the penalty:be punished#25",
    "pÅnÅ, pÅnere, posuÄ«, positus#put, place, put up#v#pono:ponere#put:place:put up#16",
    "porta, portae, f.#gate#n#porta#gate#8",
    "portÅ, portÄre, portÄvÄ«, portÄtus#carry#v#fero:ferre:porto:portare#carry#3",
    "possum, posse#can, be able#v#possum:posse#can:be able#13",
    "post + acc#after, behind#p#post#after:behind#9",
    "posteÄ (indecl.)#afterwards#d#postea#afterwards#18",
    "postquam (indecl.)#after, when#x#postquam#after:when#6",
    "postrÄ«diÄ“ (indecl.)#on the next day#d#postridie#on the next day#16",
    "postulÅ, postulÄre, postulÄvÄ«, postulÄtus#demand#v#postulo:postulare#demand#8",
    "praebeÅ, praebÄ“re, praebuÄ«, praebitus#provide#v#praebeo:praebere#provide#26",
    "praemium, praemiÄ«, n.#prize, reward, profit#n#praemium#prize:reward:profit#27",
    "prÄ«mus, prÄ«ma, prÄ«mum#first#a#primus#first#11",
    "prÄ«nceps, prÄ«ncipis, m.#chief, chieftain, emperor#n#princeps#chief:chieftain:emperor#15",
    "prÅ + abl (also used as prefix with verbs)#in front of, for, in return for (as prefix = forwards)#p#pro#in front of:for:in return for#18",
    "prÅcÄ“dÅ, prÅcÄ“dere, prÅcessÄ«#advance, proceed#v#procedo:procedere#advance:proceed#9",
    "prÅgredior, prÅgredÄ«, prÅgressus sum#advance#v#progredior:progredi#advance#34",
    "prÅmittÅ, prÅmittere, prÅmÄ«sÄ«, prÅmissus#promise#v#promitto:promittere#promise#11",
    "prope + acc#near#p#prope#near#7",
    "propter + acc#because of#p#propter#because of#0",
    "proximus, proxima, proximum#nearest, next to#a#proximus#nearest:next to#27",
    "puella, puellae, f.#girl#n#puella#girl#5",
    "puer, puerÄ«, m.#boy#n#puer#boy#8",
    "pugnÅ, pugnÄre, pugnÄvÄ«#fight#v#pugno:pugnare#fight#8",
    "pulcher, pulchra, pulchrum#beautiful, handsome#a#pulcher#beautiful:handsome#9",
    "puto, putÄre, putÄvÄ«, putÄtus#think#v#cogito:cogitare:puto:putare#think#0",
    "quaerÅ, quaerere, quaesÄ«vÄ«, quaesÄ«tus#search for, look for, ask#v#quaero:quaerere#search for:look for:ask#4",
    "quÄlis, quÄle?#what sort of?#a#qualis#what sort of#27",
    "quam (indecl.)#than, how ... ? how ... !#d#quam#than:how#10",
    "quamquam (indecl.)#although#x#quamquam#although#14",
    "quantus, quanta, quantum?#how big? how much?#a#quantus#how big:how much#22",
    "quattuor (indecl.)#four#a#quattuor#four#20",
    "-que (indecl.) (added to end of a word)#and#x#ac:atque:et:-que:que#and#14",
    "quÄ«, quae, quod#who, which#r#qui#who:which#15",
    "quÄ«nque (indecl.)#five#a#quinque#five#20",
    "quis, quid?#who? what?#r#quis#who:what#4",
    "quÅ? (indecl.)#where to?#d#quo#where to#18",
    "quod (indecl.)#because#x#quod#because#6",
    "quÅ modÅ? (indecl.)#how? in what way?#d#quo modo#how:in what way#22",
    "quoque (indecl.)#also, too#x#etiam:quoque#also:too#2",
    "quot? (indecl.)#how many?#a#quot#how many#26",
    "rapiÅ, rapere, rapuÄ«, raptus#seize, grab#v#rapio:rapere#seize:grab#0",
    "re- (prefix used with verbs)#back#x#re:re-#back#0",
    "reddÅ, reddere, reddidÄ«, redditus#give back, restore#v#reddo:reddere#give back:restore#4",
    "redeÅ, redÄ«re, rediÄ«#go back, come back, return#v#redeo:redire#go back:come back:return#15",
    "referÅ, referre, rettulÄ«, relÄtus#bring/carry back; report, tell#v#refero:referre#bring back:carry back:report:tell#26",
    "rÄ“gÄ«na, rÄ“gÄ«nae, f.#queen#n#regina#queen#33",
    "regredior, regredÄ«, regressus sum#go back, return#v#regredior:regredi#go back:return#34",
    "relinquÅ, relinquere, relÄ«quÄ«, relictus#leave, leave behind#v#discedo:discedere:relinquo:relinquere#leave:leave behind#20",
    "rÄ“s, reÄ«, f.#thing, business, matter#n#res#thing:business:matter#6",
    "resistÅ, resistere, restitÄ« + dat#resist#v#resisto:resistere#resist#17",
    "respondeÅ, respondÄ“re, respondÄ«, respÅnsus#reply#v#respondeo:respondere#reply#3",
    "rÄ“x, rÄ“gis, m.#king#n#rex#king#14",
    "rÄ«deÅ, rÄ«dÄ“re, rÄ«sÄ«#laugh, smile#v#rideo:ridere#laugh:smile#3",
    "rogÅ, rogÄre, rogÄvÄ«, rogÄtus#ask, ask for#v#rogo:rogare#ask:ask for#7",
    "RÅma, RÅmae, f.#Rome#n#Roma#Rome#0",
    "RÅmae#at/in Rome#d#Romae#at Rome:in Rome#0",
    "RÅmÄnus, RÅmÄna, Romanum#Roman#a#Romanus#Roman#0",
    "sacer, sacra, sacrum#sacred#a#sacer#sacred#21",
    "saepe (indecl.)#often#d#saepe#often#8",
    "saevus, saeva, saevum#savage, cruel#a#crudelis:saevus#savage:cruel#26",
    "salÅ«tÅ, salÅ«tÄre, salÅ«tÄvÄ«, salÅ«tÄtus#greet#v#saluto:salutare#greet#2",
    "sanguis, sanguinis, m.#blood#n#sanguis#blood#8",
    "scio, scÄ«re, scÄ«vÄ«, scÄ«tus#know#v#scio:scire#know#23",
    "scrÄ«bÅ, scrÄ«bere, scrÄ«psÄ«, scrÄ«ptus#write#v#scribo:scribere#write#6",
    "sÄ“, suÄ«#himself, herself, itself, themselves#r#ipse:se#himself:herself:itself:themselves#13",
    "sed (indecl.)#but#x#sed#but#4",
    "sedeÅ, sedÄ“re, sÄ“dÄ«#sit#v#sedeo:sedere#sit#1",
    "semper (indecl.)#always#d#semper#always#10",
    "senÄtor, senÄtÅris, m.#senator#n#senator#senator#11",
    "senex, senis (m.)#old; old man#an#senex#old:old man#5",
    "sentiÅ, sentÄ«re, sÄ“nsÄ«, sÄ“nsus#feel, notice#v#sentio:sentire#feel:notice#12",
    "septem (indecl.)#seven#a#septem#seven#20",
    "sequor, sequÄ«, secÅ«tus sum#follow#v#sequor:sequi#follow#34",
    "servÅ, servÄre, servÄvÄ«, servÄtus#save, look after#v#servo:servare#save:look after#10",
    "servus, servÄ«, m.#slave#n#servus#slave#1",
    "sex (indecl.)#six#a#sex#six#20",
    "sÄ« (indecl.)#if#x#si#if#26",
    "sÄ«c (indecl.)#thus, in this way#d#ita:sic#thus:in this way#28",
    "sÄ«cut (indecl.)#just as, like#d#sicut#just as:like#20",
    "signum, signÄ«, n.#sign, signal, seal#n#signum#sign:signal:seal#4",
    "silva, silvae, f.#wood#n#silva#wood#8",
    "simulac, simulatque#as soon as#x#simulac:simulatque#as soon as#16",
    "sine + abl#without#p#sine#without#0",
    "sÅlus, sÅla, sÅlum#alone, lonely, only, on oneâ€™s own#a#solus#alone:lonely:only:on one's own:on ones own#10",
    "soror, sorÅris, f.#sister#n#soror#sister#30",
    "spectÅ, spectÄre, spectÄvÄ«, spectÄtus#look at, watch#v#specto:spectare#look at:watch#5",
    "spÄ“s, speÄ«, f.#hope#n#spes#hope#28",
    "statim (indecl.)#at once, immediately#d#statim#at once:immediately#8",
    "stÅ, stÄre, stetÄ«#stand#v#sto:stare#stand#5",
    "stultus, stulta, stultum#stupid, foolish#a#stultus#stupid:foolish#11",
    "sub + acc/abl (also used as prefix with verbs)#under, beneath (as prefix = under, up to)#p#sub#under:beneath#27",
    "subitÅ (indecl.)#suddenly#d#subito#suddenly#6",
    "sum, esse, fuÄ«#be#v#sum:esse#be#1",
    "summus, summa, summum#highest, greatest, top (of)#a#summus#highest:greatest:top#16",
    "superÅ, superÄre, superÄvÄ«, superÄtus#overcome, overpower#v#supero:superare#overcome:overpower#6",
    "surgÅ, surgere, surrÄ“xÄ«#get up, stand up, rise#v#surgo:surgere#get up:stand up:rise#3",
    "suus, sua, suum#his, her, its, their (own)#r#suus#his:her:its:their#10",
    "taberna, tabernae, f.#shop, inn#n#taberna#shop:inn#3",
    "taceÅ, tacÄ“re, tacuÄ«, tacitus#be silent, be quiet#v#taceo:tacere#be silent:be quiet#10",
    "tÄlis, tÄle#such#a#talis#such#23",
    "tam (indecl.)#so#d#ita:tam#so#20",
    "tamen (indecl.)#however#x#tamen#however#7",
    "tandem (indecl.)#at last, finally#d#tandem#at last:finally#12",
    "tantus, tanta, tantum#so great, such a great, so much#a#tantus#so great:such a great:so much#27",
    "templum, templÄ«, n.#temple#n#templum#temple#12",
    "tempus, temporis, n.#time#n#tempus#time#0",
    "teneÅ, tenÄ“re, tenuÄ«, tentus#hold, keep, possess#v#teneo:tenere#hold:keep:possess#15",
    "terra, terrae, f.#ground, land#n#terra#ground:land#12",
    "terreÅ, terrÄ“re, terruÄ«, territus#frighten#v#terreo:terrere#frighten#7",
    "timeÅ, timÄ“re, timuÄ«#fear, be afraid#v#timeo:timere#fear:be afraid#12",
    "tollÅ, tollere, sustulÄ«, sublÄtus#raise, lift up#v#tollo:tollere#raise:lift up#16",
    "tot (indecl.)#so many#a#tot#so many#19",
    "tÅtus, tÅta, tÅtum#whole#a#totus#whole#8",
    "trÄdÅ, trÄdere, trÄdidÄ«, trÄditus#hand over#v#trado:tradere#hand over#9",
    "trahÅ, trahere, trÄxÄ«, tractus#drag, draw, pull#v#traho:trahere#drag:draw:pull#13",
    "trÄns + acc (also used as prefix with verbs)#across#p#trans#across#0",
    "trÄ“s, tria#three#a#tres#three#12",
    "trÄ«stis, trÄ«ste#sad#a#miser:tristis#sad#24",
    "tÅ«, tuÄ«#you (singular)#r#tu#you#4",
    "tum (indecl.)#then#d#deinde:tum#then#6",
    "turba, turbae, f.#crowd#n#turba#crowd#5",
    "tÅ«tus, tÅ«ta, tÅ«tum#safe#a#tutus#safe#22",
    "tuus, tua, tuum#your (singular), yours#r#tuus#your:yours#6",
    "ubi (indecl.)#where, when, where?#d#ubi#where:when:where#5",
    "umquam (indecl.)#ever#d#umquam#ever#23",
    "unde (indecl.)#from where#d#unde#from where#21",
    "Å«nus, Å«na, Å«num#one#a#unus#one#12",
    "urbs, urbis, f.#city#n#urbs#city#5",
    "ut (indecl.) + subjunc.#that, so that, in order that#x#ut#that:so that:in order that#26",
    "ut (indecl.) + indic.#as#x#ut#as#28",
    "uxor, uxÅris, f.#wife#n#uxor#wife#10",
    "vehementer (indecl.)#violently, loudly, strongly#d#vehementer#violently:loudly:strongly#10",
    "vÄ“ndÅ, vÄ“ndere, vÄ“ndidÄ«, vÄ“nditus#sell#v#vendo:vendere#sell#6",
    "veniÅ, venÄ«re, vÄ“nÄ«#come#v#venio:venire#come#5",
    "verbum, verbÄ«, n.#word#n#verbum#word#22",
    "vÄ“rus, vÄ“ra, vÄ“rum#true, real#a#verus#true:real#33",
    "vester, vestra, vestrum#your (plural), yours#r#vester#your:yours#29",
    "vestÄ«menta, vestÄ«mentÅrum, n.pl.#clothes#n#vestimenta#clothes#34",
    "via, viae, f.#street, road, way#n#via#street:road:way#1",
    "videÅ, vidÄ“re, vÄ«dÄ«, vÄ«sus#see#v#video:videre#see#3",
    "vÄ«lla, vÄ«llae, f.#house, country house#n#villa#house:country house#0",
    "vincÅ, vincere, vÄ«cÄ«, victus#conquer, win, be victorious#v#vinco:vincere#conquer:win:be victorious#15",
    "vÄ«num, vÄ«nÄ«, n.#wine#n#vinum#wine#3",
    "vir, virÄ«, m.#man#n#homo:vir#man#11",
    "vÄ«ta, vÄ«tae, f.#life#n#vita#life#13",
    "vÄ«vÅ, vÄ«vere, vÄ«xÄ«#live, be alive#v#habito:habitare:vivo:vivere#live:be alive#19",
    "vÄ«vus, vÄ«va, vÄ«vum#alive, living#a#vivus#alive:living#29",
    "vix (indecl.)#scarcely, hardly, with difficulty#d#vix#scarcely:hardly:with difficulty#19",
    "vocÅ, vocÄre, vocÄvÄ«, vocÄtus#call#v#voco:vocare#call#4",
    "volÅ, velle, voluÄ«#want#v#cupio:cupere:volo:velle#want#13",
    "vÅs, vestrum#you (plural)#r#vos#you#10",
    "vÅx, vÅcis, f.#voice, shout#n#clamo:clamor:vox#voice:shout#19",
    "vulnus, vulneris, n.#wound#n#vulnus#wound#20",
    "vultus, vultÅ«s, m.#expression, face#n#vultus#expression:face#0"
]
